# Generated by Django 5.0.6 on 2024-05-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('executor_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('executor_experience', models.TextField(verbose_name='Опыт')),
            ],
        ),
    ]
